services:
  keycloak.rtech.com:
    build:
      context: .
      dockerfile: Dockerfile
    image: keycloak.rtech.com
    container_name: keycloak.rtech.com
    restart: always
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KC_BOOTSTRAP_ADMIN_USERNAME}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KC_BOOTSTRAP_ADMIN_PASSWORD}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
      - KC_DB=${KC_DB}
      - KC_DB_URL_HOST=${KC_DB_URL_HOST}
      - KC_DB_URL_PORT=${KC_DB_URL_PORT}
      - KC_DB_URL_DATABASE=${KC_DB_URL_DATABASE}
      - KC_DB_SCHEMA=${KC_DB_SCHEMA}
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
    ports:
      - 8081:8081
      - 8443:8443
      - 9000:9000
    command: ["start-dev"]
    networks:
      - rtech-network

networks:
  rtech-network:
    external: true