services:
  nginx.rtech.com:
    build:
      context: .
      dockerfile: Dockerfile
    image: nginx.rtech.com
    container_name: nginx.rtech.com
    ports:
      - 80:80
    restart: always
    networks:
      - rtech-network

networks:
  rtech-network:
    external: true